language: java

jdk:
  - oraclejdk8

dist: trusty

addons:
  sonarcloud:
    organization: "imcamilo-github"
    token:
      secure: $SONAR_TOKEN
    branches:
      - master

script:
  - ./gradlew check
  - ./gradlew clean
  - ./gradlew build
  - ./gradlew test
  - sonar-scanner