language: java

jdk:
  - oraclejdk8

dist: trusty

addons:
  sonarcloud:
    organization: "imcamilo-github"
    token:
      secure: $SONAR_TOKEN
script
  - ./gradlew check
  - ./gradlew clean
  - ./gradlew build
  - sonar-scanner