server:
  port: 8766

endpoints:
    users: https://jsonplaceholder.typicode.com/users
    albums: https://jsonplaceholder.typicode.com/albums
    photos: https://jsonplaceholder.typicode.com/photos
    posts: https://jsonplaceholder.typicode.com/posts
    comments: https://jsonplaceholder.typicode.com/comments

spring:
  h2:
    console:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:import.sql
