server:
  port: 8766

endpoints:
    users: https://jsonplaceholder.typicode.com/users
    albums: https://jsonplaceholder.typicode.com/albums
    photos: https://jsonplaceholder.typicode.com/photos

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:import.sql
    url: jdbc:h2:mem:mydb
    username: qwerty
    password: qwerty
