server:
  port: 8766

endpoints:
    users: https://jsonplaceholder.typicode.com/users
    albums: https://jsonplaceholder.typicode.com/albums
    photos: https://jsonplaceholder.typicode.com/photos

spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:import.sql
